### PR TITLE
a misc logo from the Lancaster cryptoparty

### PR DESCRIPTION
**Pull request by brewcore**

### CODE REVIEW

**Comment by strugee** [comment]
This seems to be cut off in https://github.com/TechLancaster/cryptoparty-artwork/blob/4d8cab12e2398342578aa39ab81235b70a1099bd/misc/cryptoparty-shades.svg?

**Comment by brewcore** [comment]
I think it's just a bug in Github's preview - the raw file works correctly when I download it.

**Comment by brewcore** [comment]
I've confirmed the image appears correctly when using Google Chrome, but not in Firefox.  I've reported the issue to Github.

**Comment by strugee** [comment]
:thumbsup: did you file an issue at isaacs/github too?

**Comment by brewcore** [comment]
Not yet, will do shortly.

**Pull request merged**
